/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAgentToolsSplatRouteImport } from './routes/api/public/agent-tools/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentToolsSplatRoute =
  ApiPublicAgentToolsSplatRouteImport.update({
    id: '/api/public/agent-tools/$',
    path: '/api/public/agent-tools/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/agent-tools/$': typeof ApiPublicAgentToolsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/agent-tools/$': typeof ApiPublicAgentToolsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/agent-tools/$': typeof ApiPublicAgentToolsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/agent-tools/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/agent-tools/$'
  id: '__root__' | '/' | '/api/public/agent-tools/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAgentToolsSplatRoute: typeof ApiPublicAgentToolsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-tools/$': {
      id: '/api/public/agent-tools/$'
      path: '/api/public/agent-tools/$'
      fullPath: '/api/public/agent-tools/$'
      preLoaderRoute: typeof ApiPublicAgentToolsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAgentToolsSplatRoute: ApiPublicAgentToolsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
