/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAgentToolsSplatRouteImport } from './routes/api/public/agent-tools/$'

const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentToolsSplatRoute =
  ApiPublicAgentToolsSplatRouteImport.update({
    id: '/api/public/agent-tools/$',
    path: '/api/public/agent-tools/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/api/public/agent-tools/$': typeof ApiPublicAgentToolsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/api/public/agent-tools/$': typeof ApiPublicAgentToolsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/api/public/agent-tools/$': typeof ApiPublicAgentToolsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/inbox' | '/api/public/agent-tools/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/inbox' | '/api/public/agent-tools/$'
  id: '__root__' | '/' | '/admin' | '/inbox' | '/api/public/agent-tools/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  InboxRoute: typeof InboxRoute
  ApiPublicAgentToolsSplatRoute: typeof ApiPublicAgentToolsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-tools/$': {
      id: '/api/public/agent-tools/$'
      path: '/api/public/agent-tools/$'
      fullPath: '/api/public/agent-tools/$'
      preLoaderRoute: typeof ApiPublicAgentToolsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  InboxRoute: InboxRoute,
  ApiPublicAgentToolsSplatRoute: ApiPublicAgentToolsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
